version: 0.2
phases:
  build:
    commands:
      - echo Building
      - ls $CODEBUILD_SRC_DIR
artifacts:
  base-directory: "frontend"
  discard-paths: yes # discard parent dir
  files:
    - "**/*"
