version: 0.2
phases:
  build:
    commands:
      - echo Building
      - mkdir tmp
      - zip -r tmp/LF1.zip lambda_functions/LF1/
      - zip -r tmp/LF2.zip lambda_functions/LF2/
      - cp cloudformation/P1_LF.yaml tmp/
artifacts:
  base-directory: "tmp"
  discard-paths: yes # discard parent dir
  files:
    - "**/*"
