AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  BucketName1:
    Type: String
    Default: NA
  BucketName2:
    Type: String
    Default: NA
  ObjectKey1:
    Type: String
    Default: NA
  ObjectKey2:
    Type: String
    Default: NA
  UploadBucket:
    Type: String
    Default: b2-bucket-11-26
  OpensearchDomainEndpoint:
    Type: String
    Default: https://search-photos-iqnht2dwn4nwyktpgelc2zhqeu.us-east-1.es.amazonaws.com
  LFRoleArn:
    Type: arn:aws:iam::764559909612:role/LFRole

Resources:
  LF1:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: LF1
      Handler: "lf1.lambda_handler"
      Role: !Ref LFRoleArn
      Runtime: "python3.11"
      Timeout: 15
      MemorySize: 128
      Code:
        S3Bucket: !Ref BucketName1
        S3Key: !Ref ObjectKey1
      Environment:
        Variables:
          BUCKET_NAME: !Ref UploadBucket
          ES_ENDPOINT: !Ref OpensearchDomainEndpoint
  LF2:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: LF2
      Handler: "lf2.lambda_handler"
      Role: !Ref LFRoleArn
      Runtime: "python3.11"
      Timeout: 15
      MemorySize: 128
      Code:
        S3Bucket: !Ref BucketName2
        S3Key: !Ref ObjectKey2
      Environment:
        Variables:
          ES_ENDPOINT: !Ref OpensearchDomainEndpoint
