AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  BucketName:
    Type: String
    Default: NA

Resources:
  LF1:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: LF1
      Handler: "lambda_function.lambda_handler"
      Role: !GetAtt LFRole.Arn
      Runtime: "python3.9"
      Timeout: 15
      MemorySize: 128
      Code:
        S3Bucket: !Ref BucketName
        S3Key: "LF1.zip"
  LF2:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: LF2
      Handler: "lambda_function.lambda_handler"
      Role: !GetAtt LFRole.Arn
      Runtime: "python3.9"
      Timeout: 15
      MemorySize: 128
      Code:
        S3Bucket: !Ref BucketName
        S3Key: "LF2.zip"

  LFRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
          Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess
